# -*- coding: utf-8 -*-
"""
LSNet 实验报告生成工具
功能：
  - 生成 HTML 报告（含表格、图表、混淆矩阵）
  - 导出 Excel 对比表（如果 openpyxl 可用）
  - 自动更新 EXPERIMENTS_SUMMARY.md

用法：
  python -m lsnet.tools.generate_report [--output-dir path] [--top-k 30] [--update-summary]
"""
import argparse
import base64
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from lsnet.tools.experiment_utils import (
    discover_experiments, load_experiment_data, get_best_result,
    TECHNIQUE_LABELS,
)
try:
    from lsnet.tools._plot_config import setup_chinese_font, force_utf8_output
    force_utf8_output()
except ImportError:
    def setup_chinese_font(): pass
    def force_utf8_output(): pass

try:
    import numpy as np
    HAS_NP = True
except ImportError:
    HAS_NP = False

try:
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    HAS_EXCEL = True
except ImportError:
    HAS_EXCEL = False


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<title>LSNet 实验报告 - {date}</title>
<style>
body {{ font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
h1 {{ color: #2C3E50; border-bottom: 3px solid #3498DB; padding-bottom: 10px; }}
h2 {{ color: #2C3E50; margin-top: 30px; }}
table {{ border-collapse: collapse; width: 100%; margin: 15px 0; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
th, td {{ padding: 8px 12px; text-align: center; border: 1px solid #ddd; }}
th {{ background: #3498DB; color: white; font-weight: 600; }}
tr:nth-child(even) {{ background: #f8f9fa; }}
tr:hover {{ background: #e8f4fd; }}
.rank-1 {{ background: #FFD700 !important; font-weight: bold; }}
.rank-2 {{ background: #C0C0C0 !important; }}
.rank-3 {{ background: #CD7F32 !important; color: white; }}
.tag {{ display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; margin: 1px; }}
.tag-mixup {{ background: #E8F5E9; color: #2E7D32; }}
.tag-ema {{ background: #E3F2FD; color: #1565C0; }}
.tag-focal {{ background: #FFF3E0; color: #E65100; }}
.tag-ls {{ background: #F3E5F5; color: #6A1B9A; }}
.tag-other {{ background: #ECEFF1; color: #37474F; }}
img {{ max-width: 100%; margin: 15px 0; border: 1px solid #ddd; border-radius: 4px; }}
.summary-box {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin: 15px 0; }}
.summary-box h3 {{ margin-top: 0; color: #2C3E50; }}
.footer {{ margin-top: 30px; padding-top: 15px; border-top: 1px solid #ddd; color: #7F8C8D; font-size: 13px; }}
</style>
</head>
<body>
<h1>📊 LSNet 实验报告</h1>
<p>生成时间: {date} | 实验总数: {total_exp} | 含训练曲线: {total_with_history}</p>

<div class="summary-box">
<h3>📈 最佳实验 Top-5</h3>
<table>
<tr><th>#</th><th>实验</th><th>测试 Acc</th><th>测试 F1</th><th>验证 Acc</th><th>技术</th></tr>
{top5_rows}
</table>
</div>

<h2>🏆 完整排名</h2>
{ranking_table}

<h2>📊 各技术家族对比</h2>
{technique_table}

<h2>📈 训练曲线叠加</h2>
{curve_images}

<div class="footer">
<p>LSNet Experiment Report - Auto-generated by lsnet/tools/generate_report.py</p>
</div>
</body>
</html>"""


def collect_all_results() -> tuple:
    exp_dirs = discover_experiments()
    all_results, with_history = [], []
    for d in exp_dirs:
        data = load_experiment_data(d)
        if not data:
            continue
        best = get_best_result(data)
        if not best:
            continue
        all_results.append(best)
        if data.get('train_history'):
            with_history.append(data)
    all_results.sort(key=lambda r: r['test_acc'], reverse=True)
    with_history.sort(key=lambda e: (e.get('cv_data') or {}).get('mean_val_acc', 0), reverse=True)
    return all_results, with_history


def generate_html_table(results: List[Dict], top_k: int = 0) -> str:
    if top_k > 0:
        results = results[:top_k]
    rows = []
    for i, r in enumerate(results, 1):
        rc = f'class="rank-{i}"' if i <= 3 else ''
        th = _format_tags_html(r['name'])
        rows.append(
            f'<tr {rc}><td>{i}</td>'
            f'<td style="text-align:left;font-size:12px">{r["short_name"][:40]}</td>'
            f'<td><b>{r["test_acc"]:.2f}</b></td>'
            f'<td>{r["test_f1"]:.2f}</td>'
            f'<td>{r["val_acc"]:.2f}</td>'
            f'<td style="text-align:left">{th}</td></tr>')
    return (f'<table><tr><th>#</th><th>实验</th><th>测试 Acc</th><th>测试 F1</th>'
            f'<th>验证 Acc</th><th>技术</th></tr>{"".join(rows)}</table>')


def generate_technique_html(results: List[Dict]) -> str:
    from lsnet.tools.experiment_utils import parse_experiment_tags
    td: Dict[str, List[float]] = {}
    for r in results:
        et = parse_experiment_tags(r['name'])
        active = [k for k, v in et.items() if v] or ['baseline']
        for t in active:
            td.setdefault(t, []).append(r['test_acc'])
    if not td:
        return "<p>无数据</p>"
    if HAS_NP:
        sorted_techs = sorted(td.items(), key=lambda x: np.mean(x[1]), reverse=True)
    else:
        sorted_techs = sorted(td.items(), reverse=True)
    rows = []
    for tech, accs in sorted_techs:
        mn = np.mean(accs) if HAS_NP else sum(accs) / len(accs)
        sd = np.std(accs) if HAS_NP else 0
        rows.append(f'<tr><td style="text-align:left">{TECHNIQUE_LABELS.get(tech, tech)}</td>'
                    f'<td>{len(accs)}</td><td><b>{mn:.2f}</b></td>'
                    f'<td>{sd:.2f}</td><td>{max(accs):.2f}</td></tr>')
    return f'<table><tr><th>技术</th><th>实验数</th><th>平均 Acc</th><th>标准差</th><th>最佳 Acc</th></tr>{"".join(rows)}</table>'


def _format_tags_html(exp_name: str) -> str:
    from lsnet.tools.experiment_utils import parse_experiment_tags
    tags = parse_experiment_tags(exp_name)
    active = [k for k, v in tags.items() if v and k != 'combo'] or ['baseline']
    css_map = {'mixup': 'tag-mixup', 'ema': 'tag-ema', 'focal': 'tag-focal', 'label_smoothing': 'tag-ls'}
    spans = []
    for t in active:
        css = css_map.get(t, 'tag-other')
        spans.append(f'<span class="tag {css}">{TECHNIQUE_LABELS.get(t, t)}</span>')
    return ''.join(spans)


def _encode_image(image_path: Path) -> str:
    if not image_path.exists():
        return ""
    with open(image_path, 'rb') as f:
        data = base64.b64encode(f.read()).decode()
    return f'<img src="data:image/png;base64,{data}" />'


def update_experiments_summary(results: List[Dict]):
    sp = Path(__file__).resolve().parent.parent / "experiments" / "EXPERIMENTS_SUMMARY.md"
    if not sp.parent.exists():
        print(f"  [WARN] 目录不存在: {sp.parent}")
        return
    lines = ["# LSNet 实验结果汇总（自动生成）\n",
             f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
             "## 实验排名\n",
             "| 排名 | 实验 | 测试 Acc | 测试 F1 | 验证 Acc | 技术 |",
             "|:---:|------|:--------:|:------:|:---------:|------|"]
    for i, r in enumerate(results[:30], 1):
        lines.append(f"| {i} | {r['short_name'][:35]} | {r['test_acc']:.2f}% | "
                     f"{r['test_f1']:.2f}% | {r['val_acc']:.2f}% | {r['technique_summary'][:50]} |")
    sp.write_text('\n'.join(lines), encoding='utf-8')
    print(f"  [OK] EXPERIMENTS_SUMMARY.md 已更新: {sp}")


def export_excel(results: List[Dict], save_path: Path):
    if not HAS_EXCEL:
        print("  [WARN] openpyxl 未安装，跳过 Excel 导出 (pip install openpyxl)")
        return
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "实验排名"
    hf = Font(bold=True, color='FFFFFF', size=11)
    hfill = PatternFill('solid', fgColor='3498DB')
    ha = Alignment(horizontal='center', vertical='center')
    tb = Border(left=Side(style='thin'), right=Side(style='thin'),
                top=Side(style='thin'), bottom=Side(style='thin'))
    headers = ['排名', '实验名', '测试Acc', '测试F1', '验证Acc', '折数', '学习率', 'Batch', '图像尺寸', '技术摘要']
    for ci, h in enumerate(headers, 1):
        c = ws.cell(row=1, column=ci, value=h)
        c.font, c.fill, c.alignment, c.border = hf, hfill, ha, tb
    for i, r in enumerate(results, 1):
        rd = [i, r['short_name'], round(r['test_acc'], 2), round(r['test_f1'], 2),
              round(r['val_acc'], 2), r['cv_folds'], r['lr'], r['batch_size'],
              r['image_size'], r['technique_summary']]
        for ci, val in enumerate(rd, 1):
            c = ws.cell(row=i + 1, column=ci, value=val)
            c.border, c.alignment = tb, Alignment(horizontal='center')
    ws.column_dimensions['B'].width = 50
    ws.column_dimensions['J'].width = 40
    wb.save(str(save_path))
    print(f"  [OK] Excel 导出: {save_path}")


def generate_run_scripts(results: List[Dict]) -> str:
    if not results:
        return ""
    best = results[0]
    cmd_parts = [
        "python lsnet/train.py \\",
        f"  --model lsnet --epochs 80 --batch-size {best.get('batch_size', 32)} \\",
        f"  --lr {best.get('lr', 0.001)} --image-size {best.get('image_size', 224)} \\",
    ]
    if best.get('label_smoothing', 0) > 0:
        cmd_parts.append(f"  --label-smoothing {best['label_smoothing']} \\")
    if best.get('mixup_alpha', 0) > 0:
        cmd_parts.append(f"  --use-mixup --mixup-alpha {best['mixup_alpha']} \\")
    from lsnet.tools.experiment_utils import parse_experiment_tags
    tags = parse_experiment_tags(best['name'])
    if tags.get('ema'):        cmd_parts.append("  --use-ema \\")
    if tags.get('focal'):      cmd_parts.append(f"  --use-focal-loss --focal-gamma {best.get('focal_gamma', 2.0)} \\")
    if tags.get('warmup'):     cmd_parts.append(f"  --warmup-epochs {best.get('warmup_epochs', 5)} \\")
    if tags.get('plantvillage'): cmd_parts.append("  --use-plantvillage \\")
    cmd_parts.append(f"  --exp-suffix {best.get('short_name', 'best_reproduction')}")
    return '\n'.join(cmd_parts)


def main():
    parser = argparse.ArgumentParser(description='LSNet 实验报告生成工具')
    parser.add_argument('--output-dir', type=str, default='', help='报告输出目录')
    parser.add_argument('--top-k', type=int, default=30, help='排名表实验数')
    parser.add_argument('--update-summary', action='store_true', help='更新 EXPERIMENTS_SUMMARY.md')
    parser.add_argument('--export-excel', type=str, default='', help='Excel 导出路径')
    args = parser.parse_args()

    setup_chinese_font()

    all_results, with_history = collect_all_results()
    if not all_results:
        print("[WARN] 未找到实验数据"); return

    out_dir = Path(args.output_dir) if args.output_dir else \
        Path(__file__).resolve().parent.parent / "results" / "reports"
    out_dir.mkdir(parents=True, exist_ok=True)

    from lsnet.tools.compare_experiments import plot_ranking_chart, plot_technique_comparison
    from lsnet.tools.visualize_results import plot_overlay_curves, plot_best_per_technique

    plot_ranking_chart(all_results, out_dir / "experiment_ranking.png")
    plot_technique_comparison(all_results, out_dir / "technique_comparison.png")
    plot_overlay_curves(with_history, out_dir)
    plot_best_per_technique(with_history, out_dir)

    top5 = all_results[:5]
    top5_rows = ""
    for i, r in enumerate(top5, 1):
        th = _format_tags_html(r['name'])
        top5_rows += (f'<tr><td><b>{i}</b></td>'
                      f'<td style="text-align:left;font-size:12px">{r["short_name"][:35]}</td>'
                      f'<td><b style="color:#27AE60">{r["test_acc"]:.2f}%</b></td>'
                      f'<td>{r["test_f1"]:.2f}%</td>'
                      f'<td>{r["val_acc"]:.2f}%</td>'
                      f'<td style="text-align:left">{th}</td></tr>\n')

    ranking_table = generate_html_table(all_results, args.top_k)
    technique_table = generate_technique_html(all_results)

    curve_images = ""
    for img_name in ['training_curves_overlay.png', 'best_per_technique.png',
                     'experiment_ranking.png', 'technique_comparison.png']:
        img_path = out_dir / img_name
        if img_path.exists():
            label = img_path.stem.replace('_', ' ').title()
            curve_images += f'<h3>{label}</h3>\n{_encode_image(img_path)}\n'

    rep_cmd = generate_run_scripts(all_results)
    if rep_cmd:
        curve_images += (f'<h3>🏆 最佳实验复现命令</h3>'
                         f'<pre style="background:#2C3E50;color:#ECF0F1;padding:15px;'
                         f'border-radius:5px;overflow-x:auto;font-size:12px">\n{rep_cmd}\n</pre>')

    html = HTML_TEMPLATE.format(
        date=datetime.now().strftime('%Y-%m-%d %H:%M'),
        total_exp=len(all_results), total_with_history=len(with_history),
        top5_rows=top5_rows, ranking_table=ranking_table,
        technique_table=technique_table, curve_images=curve_images)

    html_path = out_dir / "experiment_report.html"
    html_path.write_text(html, encoding='utf-8')
    print(f"  [OK] HTML 报告: {html_path}")

    if args.update_summary:
        update_experiments_summary(all_results)

    excel_path = Path(args.export_excel) if args.export_excel else out_dir / "experiment_report.xlsx"
    export_excel(all_results, excel_path)

    print(f"\n[OK] 报告生成完成 | {html_path}")


if __name__ == '__main__':
    main()
